version: "2"
services:
  btc-fsm-sync:
    container_name: btc-fsm-sync
    image: btc/script-for-load-testing
    volumes:
      - ./src/main/docker/package.yaml:/app/config/package.yaml
    mem_limit: 512m
    ports:
      - "8080:8080"
#    networks:
#      btc-net:
#
#  # Эта команда подключит заглушки API к сети с сервисами btc
#networks:
#  btc-net:
#    name: btc-net