version: '2.1'

services:

  # Infinispan prior to 13.x had different config
  infinispan:
    image: infinispan/server:13.0.2.Final
    container_name: infinispan
    ports:
      - "11222:11222"
    command: "-c infinispan-demo.xml"
    volumes:
      - ./infinispan/infinispan.xml:/opt/infinispan/server/conf/infinispan-demo.xml:z
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:11222/rest/v2/cache-managers/default/health/status"
        ]
      interval: 1s
      timeout: 30s
      retries: 50
    networks:
      - kogito-network

  zookeeper:
    container_name: zookeeper
    image: strimzi/kafka:0.20.1-kafka-2.6.0
    command:
      [
        "sh",
        "-c",
        "bin/zookeeper-server-start.sh config/zookeeper.properties"
      ]
    ports:
      - "2181:2181"
    environment:
      LOG_DIR: "/tmp/logs"
    networks:
      - kogito-network

  kafka:
    image: strimzi/kafka:0.20.1-kafka-2.6.0
    container_name: kafka
    command:
      [
        "sh",
        "-c",
        "bin/kafka-server-start.sh config/server.properties --override inter.broker.listener.name=$${KAFKA_INTER_BROKER_LISTENER_NAME} --override listener.security.protocol.map=$${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP} --override listeners=$${KAFKA_LISTENERS} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT}"
      ]
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      LOG_DIR: "/tmp/logs"
    networks:
      - kogito-network

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8081:8080
    depends_on:
      - zookeeper
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      KAFKA_CLUSTERS_0_JMXPORT: 9997
    networks:
      - kogito-network

  keycloak:
    container_name: keycloak
    image: jboss/keycloak
    ports:
      - "8480:8080"
    volumes:
      - ./keycloak/:/tmp/kogito/:z
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:8080/auth/realms/kogito"
        ]
      interval: 1s
      timeout: 30s
      retries: 100
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/kogito/kogito-realm.json
    networks:
      - kogito-network

  data-index:
    container_name: data-index
    image: quay.io/kiegroup/kogito-data-index-infinispan:${KOGITO_VERSION}
    ports:
      - "8180:8080"
    depends_on:
      kafka:
        condition: service_started
      infinispan:
        condition: service_healthy
    volumes:
      - ./persistence/:/home/kogito/data/protobufs/:z
    environment:
      QUARKUS_INFINISPAN_CLIENT_SERVER_LIST: infinispan:11222
      QUARKUS_INFINISPAN_CLIENT_USE_AUTH: "false"
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      KOGITO_DATA_INDEX_PROPS: -Dkogito.protobuf.folder=/home/kogito/data/protobufs/
    networks:
      - kogito-network

  jobs-service:
    container_name: jobs-service
    # network_mode: "host"
    image: quay.io/kiegroup/kogito-jobs-service-infinispan:${KOGITO_VERSION}
    ports:
      - 8580:8580
    depends_on:
      kafka:
        condition: service_started
      infinispan:
        condition: service_healthy
      data-index:
        condition: service_started
    environment:
      QUARKUS_INFINISPAN_CLIENT_SERVER_LIST: infinispan:11222
      QUARKUS_INFINISPAN_CLIENT_USE_AUTH: "false"
      ENABLE_EVENTS: "true"
      KOGITO_JOBS_PROPS: -Dquarkus-profile=events-support -D%events-support.quarkus.http.port=8580 -D%events-support.kafka.bootstrap.servers=kafka:9092 -D%events-support.mp.messaging.outgoing.kogito-job-service-job-status-events.bootstrap.servers=kafka:9092 -Dkogito.service.url=http://${DOCKER_GATEWAY_HOST}:8580
    networks:
      - kogito-network

  management-console:
    container_name: management-console
    image: quay.io/kiegroup/kogito-management-console:${KOGITO_VERSION}
    ports:
      - 8280:8080
    depends_on:
      data-index:
        condition: service_started
      jobs-service:
        condition: service_started
      keycloak:
        condition: service_healthy
    volumes:
      - ./svg/:/home/kogito/data/svg/:z
    environment:
      KOGITO_DATAINDEX_HTTP_URL: http://${DOCKER_GATEWAY_HOST}:8180/graphql
      KOGITO_MANAGEMENT_CONSOLE_PROPS: -Dkogito.consoles.keycloak.config.url=http://${DOCKER_GATEWAY_HOST}:8480/auth -Dkogito.consoles.keycloak.config.health-check-url=http://${DOCKER_GATEWAY_HOST}:8480/auth/realms/kogito/.well-known/openid-configuration -Dkogito.svg.folder.path=/home/kogito/data/svg
    networks:
      - kogito-network

  kogito-autopayment-stub:
    container_name: kogito-autopayment-stub
    build:
      context: ../kogito-autopayment-stub
      dockerfile: ../kogito-autopayment-stub/src/main/docker/Dockerfile.jvm
    ports:
      - 8082:8080
    # Hack to make runtime management work, see https://github.com/kiegroup/kogito-apps/pull/1025
    environment:
      JAVA_OPTIONS: -Dkogito.service.url=http://${DOCKER_GATEWAY_HOST}:8080
    depends_on:
      kafka:
        condition: service_started
      infinispan:
        condition: service_healthy
      jobs-service:
        condition: service_started
      data-index:
        condition: service_started
    networks:
      - kogito-network

  kogito-autopayment:
    container_name: kogito-autopayment
    build:
      context: ../kogito-autopayment
      dockerfile: ../kogito-autopayment/src/main/docker/Dockerfile.jvm
    ports:
      - 8080:8080
    # Hack to make runtime management work, see https://github.com/kiegroup/kogito-apps/pull/1025
    environment:
      # JAVA_OPTIONS: -Dquarkus-profile=infinispan -Dkogito.service.url=http://${DOCKER_GATEWAY_HOST}:8080
      # JAVA_OPTIONS: -Dquarkus-profile=kafka -Dkogito.service.url=http://${DOCKER_GATEWAY_HOST}:8080
      # JAVA_OPTIONS: -Dquarkus-profile=postgresql -Dkogito.service.url=http://${DOCKER_GATEWAY_HOST}:8080
      JAVA_OPTIONS: -Dquarkus-profile=mongo -Dkogito.service.url=http://${DOCKER_GATEWAY_HOST}:8080
    depends_on:
      kafka:
        condition: service_started
      infinispan:
        condition: service_healthy
      jobs-service:
        condition: service_started
      data-index:
        condition: service_started
    networks:
      - kogito-network

  postgresql:
    container_name: postgresql
    image: postgres:14.2-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: kogito
      POSTGRES_PASSWORD: kogito
      POSTGRES_DB: kogito
    networks:
      - kogito-network

  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: kogito
      MONGO_INITDB_ROOT_PASSWORD: kogito
    networks:
      - kogito-network

  prometheus:
    image: prom/prometheus:v2.8.0
    volumes:
      - ./prometheus/:/etc/prometheus/:z
    command: '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
    depends_on:
      - kogito-autopayment
    networks:
      - kogito-network

  grafana:
    image: grafana/grafana:6.6.1
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana/:/etc/grafana/:z
    networks:
      - kogito-network

networks:
  kogito-network:
    driver: bridge
    name: kogito-network
