{
 "title": "kogito-autopayment_1.20.0.Final - Global - Operational Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Global instances started",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(kogito_process_instance_started_total)"
    }
   ]
  },
  {
   "title": "Global running instances",
   "type": "stat",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(kogito_process_instance_running_total)"
    }
   ]
  },
  {
   "title": "Global completed instances",
   "type": "stat",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(kogito_process_instance_completed_total)"
    }
   ]
  },
  {
   "title": "Global SLA violated instances",
   "type": "stat",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(kogito_process_instance_sla_violated_total)"
    }
   ]
  },
  {
   "title": "Global process execution time",
   "type": "graph",
   "gridPos": { "x": 0, "y": 16, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(kogito_process_instance_duration_seconds_sum[1m])/avg_over_time(kogito_process_instance_duration_seconds_count[1m])",
     "legendFormat": "{{artifact_id}}"
    }
   ]
  }
 ]
}