version: "2"
services:
  api-mock-rest:
    container_name: api-mock-rest
    image: danielgtaylor/apisprout
    mem_limit: 50m
    ports:
      - "8000:8000"
    volumes:
      - ./apis:/apis:z
    command: /apis/rest.yaml
#    networks:
#      sberflow-net:

# Эта команда подключит заглушки API к сети с сервисами SberFlow
# networks:
#   sberflow-net:
#     external: true
#     name: sberflow-net