kind: ConfigMap
apiVersion: v1
metadata:
  name: kafka-to-db-kogito
  namespace: kogito-operator-system
  selfLink: /api/v1/namespaces/kogito-operator-system/configmaps/kafka-to-db-kogito
  uid: a33194c0-50e2-4563-abdd-3927c6bb7d6b
  resourceVersion: '39886448'
  creationTimestamp: '2022-04-29T07:54:04Z'
  labels:
    app.kubernetes.io/instance: kafka-to-db-kogito
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kafka-to-db
    app.kubernetes.io/version: 1.0.1
    distribVersion: 1.0.1
    helm.sh/chart: kafka-to-db-1.0.1
  annotations:
    meta.helm.sh/release-name: kafka-to-db
    meta.helm.sh/release-namespace: kogito-operator-system
  managedFields:
    - manager: dashboard
      operation: Update
      apiVersion: v1
      time: '2022-04-29T08:12:46Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:JAVA_OPTS: {}
          f:application.yml: {}
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:app.kubernetes.io/version: {}
            f:distribVersion: {}
            f:helm.sh/chart: {}
data:
  JAVA_OPTS: |-
    -Dnode.id=${HOSTNAME}
    -Dspring.profiles.active=dev
    -DloggingDir=/home/jboss/logs
    -DloggingJSONFile=log.json
    -Dfile.encoding=UTF-8
  application.yml: |-
    module.id: kafka-to-db

    logging:
      level:
        ROOT: INFO

    server:
      port: 8088

    spring:
      kafka:
        bootstrap-servers: 10.31.0.5:31543

        eventsTopic: kogito-processinstances-events

        listener:
          concurency: 4
        consumer:
          groupId: kogito_to_db
          enable-auto-commit: true
          auto-offset-reset: earliest

          properties:
            spring.json.use.type.headers: false
            max.poll.interval.ms: 35000
            session.timeout.ms: 30000
      json:
        use:
          type:
            headers: false

    management:
      endpoints:
        enabled-by-default: false
        web.exposure.include: health,metrics,threaddump,prometheus
      endpoint:
        metrics.enabled: true
        health:
          enabled: true
          probes:
            enabled: true
          show-details: when_authorized
        threaddump.enabled: true
        prometheus.enabled: true

    database:
      driverClassName: org.postgresql.Driver
      jdbcUrl: jdbc:postgresql://10.31.0.2:5432/newdb
      username: kogito
      password: a29naXRv
      schema: kafka

