apiVersion: app.kiegroup.org/v1beta1
kind: KogitoBuild
metadata:
  name: kogitobpmn
spec:
  type: RemoteSource
  env:
  - name: CUSTOM_ENV
    value: "env_value"
  gitSource:
    contextDir: kogitobpmn
  #TODO:  uri: 'https://github.com/kiegroup/kogito-examples'
  # set your maven nexus repository to speed up the build time
  #mavenMirrorURL:
---
apiVersion: app.kiegroup.org/v1beta1
kind: KogitoRuntime
metadata:
  name: kogitobpmn