{
 "title": "Kogito Metrics",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "dataSource", "query": "postgres" }
  ]
 },
 "panels": [
  {
   "title": "Процессов стартовано",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select to_char(p.starttime, 'YYYY-MM-DD HH24:MI:SS')::timestamp as time,\n       p.processName,       \n       count(1) as \" \"\nfrom ProcessInstance p\nwhere p.starttime between (timestamp $__timeFrom()) and (timestamp $__timeTo())\ngroup by to_char(p.starttime, 'YYYY-MM-DD HH24:MI:SS'), p.processName\norder by 1,2"
    }
   ]
  },
  {
   "title": "Процессов завершено",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select to_char(p.endtime, 'YYYY-MM-DD HH24:MI:SS')::timestamp as time,\n       p.processName,       \n       count(1) as \" \"\nfrom ProcessInstance p\nwhere p.endtime between (timestamp $__timeFrom()) and (timestamp $__timeTo())\ngroup by to_char(p.endtime, 'YYYY-MM-DD HH24:MI:SS'), p.processName\norder by 1,2"
    }
   ]
  },
  {
   "title": "Процессы Pass/Failure rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ]
  },
  {
   "title": "Процессы Pass/Failure rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "select timestamp $__timeFrom() as time, t1.processname, count(t2.cnt) * 100 / count(t1.cnt) as \" \"\nfrom (select p1.processName, count(1) as cnt\nfrom ProcessInstance p1\nwhere p1.starttime between timestamp $__timeFrom() and timestamp $__timeTo()\ngroup by p1.processName) t1\nleft join (select p2.processName, count(1) as cnt\nfrom ProcessInstance p2\nwhere p2.starttime between timestamp $__timeFrom() and timestamp $__timeTo() and p2.state = 2\ngroup by p2.processName) t2 on t2.processname = t1.processname\ngroup by t1.processName"
    }
   ]
  },
  {
   "title": "Длительность выполнения процесса (ms)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select to_char(p.starttime, 'YYYY-MM-DD HH24:MI:SS')::timestamp as time,\n       p.processName,       \n       avg((EXTRACT('epoch' from p.endtime) - EXTRACT('epoch' from p.starttime)) * 1000) as \" \"\nfrom ProcessInstance p\nwhere p.endtime is not null \nand p.starttime between (timestamp $__timeFrom()) and (timestamp $__timeTo())\ngroup by to_char(p.starttime, 'YYYY-MM-DD HH24:MI:SS'), p.processName\norder by 1,2"
    }
   ]
  },
  {
   "title": "Ошибки",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select to_char(p.endtime, 'YYYY-MM-DD HH24:MI:SS')::timestamp as time,\n       p.processName,       \n       count(1) as \" \"\nfrom ProcessInstance p\nwhere p.error is not null\nand p.endtime between (timestamp $__timeFrom()) and (timestamp $__timeTo())\ngroup by to_char(p.endtime, 'YYYY-MM-DD HH24:MI:SS'), p.processName\norder by 1,2"
    }
   ]
  },
  {
   "title": "Завершено шагов в секунду",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select to_char(n.endtime, 'YYYY-MM-DD HH24:MI:SS')::timestamp as time,\n       p.processName,\n       count(1) as \" \"\nfrom ProcessInstance p\njoin NodeInstance n on n.processinstanceid = p.id and n.endtime is not null\nwhere n.endtime between (timestamp $__timeFrom()) and (timestamp $__timeTo())\ngroup by to_char(n.endtime, 'YYYY-MM-DD HH24:MI:SS'), p.processName\norder by 1,2"
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select to_char(j.time, 'YYYY-MM-DD HH24:MI:SS')::timestamp as time,\n       p.processName || ' ' || j.status as status,\n       count(1) as \" \"\nfrom Jobs j\njoin ProcessInstance p on p.id = j.ProcessInstanceId\nwhere j.time between (timestamp $__timeFrom()) and (timestamp $__timeTo())\ngroup by to_char(j.time, 'YYYY-MM-DD HH24:MI:SS'), p.processName, j.status\norder by 1,2"
    }
   ]
  }
 ]
}