{
 "title": "Kogito Pods",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_pod_info, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{cluster=\"$cluster\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "kogito-bpmn-async", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage [kogito-bpmn-async]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{cluster=\"$cluster\", namespace=\"$namespace\", container=\"kogito-bpmn-async\"}) by (container, pod)",
     "legendFormat": "[{{container}}] {{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage [kogito-bpmn-async]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"$namespace\", container=\"kogito-bpmn-async\", image!=\"\"}) by (container, pod)",
     "legendFormat": "[{{container}}] {{pod}}"
    }
   ]
  },
  { "title": "infinispan", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "CPU Usage [infinispan]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{cluster=\"$cluster\", namespace=\"$namespace\", container=\"infinispan\"}) by (container, pod)",
     "legendFormat": "[{{container}}] {{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage [infinispan]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"$namespace\", container=\"infinispan\", image!=\"\"}) by (container, pod)",
     "legendFormat": "[{{container}}] {{pod}}"
    }
   ]
  },
  { "title": "data-index", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "CPU Usage [data-index]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{cluster=\"$cluster\", namespace=\"$namespace\", container=\"data-index\"}) by (container, pod)",
     "legendFormat": "[{{container}}] {{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage [data-index]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"$namespace\", container=\"data-index\", image!=\"\"}) by (container, pod)",
     "legendFormat": "[{{container}}] {{pod}}"
    }
   ]
  },
  { "title": "jobs-service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "CPU Usage [jobs-service]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{cluster=\"$cluster\", namespace=\"$namespace\", container=\"jobs-service\"}) by (container, pod)",
     "legendFormat": "[{{container}}] {{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage [jobs-service]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"$namespace\", container=\"jobs-service\", image!=\"\"}) by (container, pod)",
     "legendFormat": "[{{container}}] {{pod}}"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{cluster=\"$cluster\", namespace=\"$namespace\", container=\"jobs-service\", resource=\"memory\"}\n)",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{cluster=\"$cluster\", namespace=\"$namespace\", container=\"jobs-service\", resource=\"memory\"}\n)",
     "legendFormat": "limits"
    }
   ]
  },
  { "title": "kafka", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "CPU Usage [kafka]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{cluster=\"$cluster\", namespace=\"$namespace\", container=\"kafka\"}) by (container, pod)",
     "legendFormat": "[{{container}}] {{pod}}"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{cluster=\"$cluster\", namespace=\"$namespace\", container=\"kafka\", resource=\"cpu\"}\n)",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{cluster=\"$cluster\", namespace=\"$namespace\", container=\"kafka\", resource=\"cpu\"}\n)\n",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "Memory Usage [kafka]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"$namespace\", container=\"kafka\", image!=\"\"}) by (container, pod)",
     "legendFormat": "[{{container}}] {{pod}}"
    }
   ]
  },
  { "title": "api-mock-rest", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "CPU Usage [api-mock-rest]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{cluster=\"$cluster\", namespace=\"$namespace\", container=\"api-mock-rest\"}) by (container, pod)",
     "legendFormat": "[{{container}}] {{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage [api-mock-rest]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"$namespace\", container=\"api-mock-rest\", image!=\"\"}) by (container, pod)",
     "legendFormat": "[{{container}}] {{pod}}"
    }
   ]
  },
  {
   "title": "http_server_connections_seconds",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 }
  },
  {
   "title": "http_server_connections_seconds_active_count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(http_server_connections_seconds_active_count [60s])",
     "legendFormat": "{{pod}} | {{service}}"
    }
   ]
  },
  {
   "title": "http_server_connections_seconds_duration_sum",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(http_server_connections_seconds_duration_sum [60s])",
     "legendFormat": "{{pod}} | {{service}}"
    }
   ]
  },
  {
   "title": "http_server_connections_seconds_max",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(http_server_connections_seconds_max [60s])",
     "legendFormat": "{{pod}} | {{service}}"
    }
   ]
  },
  { "title": "http_server_requests_seconds", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "http_server_requests_seconds_count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_count [60s])",
     "legendFormat": "{{pod}} | {{service}}"
    }
   ]
  },
  {
   "title": "http_server_requests_seconds_sum",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_sum [60s])",
     "legendFormat": "{{pod}} | {{service}}"
    }
   ]
  },
  {
   "title": "http_server_requests_seconds_max",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_max [60s])",
     "legendFormat": "{{pod}} | {{service}}"
    }
   ]
  },
  { "title": "http_server_bytes_written", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 } },
  {
   "title": "http_server_bytes_written_count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 99 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(http_server_bytes_written_count [60s])",
     "legendFormat": "{{pod}} | {{service}}"
    }
   ]
  },
  {
   "title": "http_server_bytes_written_sum",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 99 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(http_server_bytes_written_sum [60s])",
     "legendFormat": "{{pod}} | {{service}}"
    }
   ]
  },
  {
   "title": "http_server_bytes_written_max",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 108 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(http_server_bytes_written_max [60s])",
     "legendFormat": "{{pod}} | {{service}}"
    }
   ]
  }
 ]
}