spring:
  sleuth:
    enabled: false

orc:
  orchestrator.extended-logging.enabled: true

  script:
    btc-fsm-sync:
      rest-service-url: http://api-mock-rest:8000
#    kafka-servers: host.docker.internal:9092