module.id: kafka-to-db
artifact.id: kafka-to-db

logging:
  level:
    ROOT: INFO

server:
  port: 8088

# подключение к Кафка
kafka:

  processinstances-events:
    bootstrap-servers: 10.31.0.5:31543
    eventsTopic: kogito-processinstances-events
    listener.concurency: 4
    consumer.groupId: kogito_to_db

  jobs-events:
    bootstrap-servers: 10.31.0.5:31543
    eventsTopic: kogito-jobs-events
    listener.concurency: 4
    consumer.groupId: kogito_to_db


# подключение к БД (пароль шифруется)
database:
  driverClassName: org.postgresql.Driver
  jdbcUrl: jdbc:postgresql://10.31.0.2:5432/newdb
  username: kogito
  password: a29naXRv
  schema:

  sizeLimit: 130000

spring:

  json:
    use:
      type:
        headers: false
