module.id: kafka-to-db
artifact.id: kafka-to-db

logging:
  level:
    ROOT: INFO

server:
  port: 8088

spring:
  # параметры подключения к kafka broker
  kafka:
    # dzo (kogito)
    bootstrap-servers: 10.31.0.5:31543

    # топик с событиями
    eventsTopic: kogito-processinstances-events

    listener:
      concurency: 4
    consumer:
      groupId: kogito_to_db
      enable-auto-commit: true
      auto-offset-reset: earliest

      properties:
        spring.json.use.type.headers: false
        # макс. задержка между запросами к брокеру
        max.poll.interval.ms: 35000
        # ttl сессии
        session.timeout.ms: 30000
#        max.partition.fetch.bytes: 2048000
#        fetch.max.bytes.config: 2048000

  json:
    use:
      type:
        headers: false

management:
  endpoints:
    enabled-by-default: false
    web.exposure.include: health,metrics,threaddump,prometheus
  endpoint:
    metrics.enabled: true
    health:
      enabled: true
      probes:
        enabled: true
      show-details: when_authorized
    threaddump.enabled: true
    prometheus.enabled: true

# подключение к БД (пароль шифруется)
database:
  driverClassName: org.postgresql.Driver
  jdbcUrl: jdbc:postgresql://10.31.0.2:5432/newdb
  username: kogito
  password: a29naXRv
  schema: kafka

