apiVersion: app.kiegroup.org/v1beta1
kind: KogitoSupportingService
metadata:
  name: data-index
spec:
  serviceType: DataIndex
  # environment variables to set in the runtime container. Example: JAVA_OPTIONS: "-Dquarkus.log.level=DEBUG"
  #env:
    # - name: JAVA_OPTIONS
    #    value: "-Dquarkus.log.level=DEBUG"
  # number of pods to be deployed
  replicas: 1
  image: dzo.sw.sbc.space/sbt_dev/ci90000011_bpmx_dev/kogito-data-index-infinispan:latest
  # Limits and requests for the Data Index pod
  #memoryLimit: ""
  #memoryRequest: ""
  #cpuLimit: ""
  #cpuRequest: ""
  # details about the kogito infra
  infra:
    - kogito-kafka-infra
    - kogito-infinispan-infra
  env:
    - name: kogito.consoles.keycloak.config.realm
      value: kogito
    - name: kogito.consoles.keycloak.config.url
      value: https://10.31.0.5:31711/auth
    - name: kogito.consoles.keycloak.config.client-id
      value: kogito-console-quarkus
    - name: kogito.consoles.keycloak.config.health-check-url
      value: https://10.31.0.5:31711/auth/realms/kogito/.well-known/openid-configuration
    - name: kogito.consoles.keycloak.config.disable-health-check
      value: "false"
    - name: kogito.consoles.keycloak.config.update-token-validity
      value: "30"
    - name: kogito.svg.folder.path
      value: /home/kogito/data/svg
