kind: Deployment
apiVersion: apps/v1
metadata:
  name: infinispan-operator-controller-manager
  uid: e1444931-0ed4-4463-aaf7-bf3c43be0e06
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: infinispan-operator
      control-plane: controller-manager
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: infinispan-operator
        control-plane: controller-manager
    spec:
      containers:
        - name: manager
          image: dzo.sw.sbc.space/sbt_dev/ci90000011_bpmx_dev/infinispan-operator:2.2.4.Final
          args:
            - operator
            - '--leader-elect'
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.annotations['olm.targetNamespaces']
            - name: RELATED_IMAGE_OPENJDK
              value: dzo.sw.sbc.space/sbt_dev/ci90000011_bpmx_dev/infinispan/server:13.0.8.Final
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: CONFIG_LISTENER_IMAGE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.annotations['containerImage']
            - name: OPERATOR_CONDITION_NAME
              value: infinispan-operator.v2.2.4
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: infinispan-operator-controller-manager
      serviceAccount: infinispan-operator-controller-manager
      securityContext: {}
      schedulerName: default-scheduler


