apiVersion: app.kiegroup.org/v1beta1
kind: KogitoSupportingService
metadata:
  name: jobs-service
spec:
  replicas: 1
  serviceType: JobsService
  image: dzo.sw.sbc.space/sbt_dev/ci90000011_bpmx_dev/kogito-jobs-service-infinispan:latest
  infra:
    - kogito-infinispan-infra
