apiVersion: app.kiegroup.org/v1beta1
kind: KogitoSupportingService
metadata:
  name: data-index
spec:
  serviceType: DataIndex
  replicas: 1
  image: dzo.sw.sbc.space/sbt_dev/ci90000011_bpmx_dev/kiegroup/kogito-data-index-infinispan:${KOGITO_INFRA_SERVICES_VERSION}
  infra:
    - kogito-kafka-infra
    - kogito-infinispan-infra
