{
 "title": "Kogito Metrics",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "dataSource", "query": "postgres" },
   {
    "name": "processName",
    "query": "select processName from ProcessInstance group by processName"
   }
  ]
 },
 "panels": [
  {
   "title": "Процессов стартовано",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select to_char(p.starttime, 'YYYY-MM-DD HH24:MI:SS')::timestamp as time,\n       p.processName,       \n       count(1) as \" \"\nfrom ProcessInstance p\nwhere p.starttime between (timestamp $__timeFrom()) and (timestamp $__timeTo())\ngroup by to_char(p.starttime, 'YYYY-MM-DD HH24:MI:SS'), p.processName\norder by 1,2"
    }
   ]
  },
  {
   "title": "Процессов завершено",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select to_char(p.endtime, 'YYYY-MM-DD HH24:MI:SS')::timestamp as time,\n       p.processName,       \n       count(1) as \" \"\nfrom ProcessInstance p\nwhere p.endtime between (timestamp $__timeFrom()) and (timestamp $__timeTo())\ngroup by to_char(p.endtime, 'YYYY-MM-DD HH24:MI:SS'), p.processName\norder by 1,2"
    }
   ]
  },
  {
   "title": "Процессы Pass/Failure rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select\n    t.time as time,\n    p1.processName,\n    count(p1.processName) * 100 / count(p2.processName) as \" \"\nfrom (select generate_series as time from pg_catalog.generate_series(\n        date_trunc('minute', timestamp $__timeFrom()),\n        date_trunc('minute', timestamp $__timeTo()), interval '1 second')) t\njoin ProcessInstance p1 on to_char(p1.starttime, 'YYYY-MM-DD HH24:MI:SS') = to_char(t.time, 'YYYY-MM-DD HH24:MI:SS') and p1.state = 2\njoin ProcessInstance p2 on to_char(p2.starttime, 'YYYY-MM-DD HH24:MI:SS') = to_char(t.time, 'YYYY-MM-DD HH24:MI:SS') and p2.processName = p1.processName\ngroup by t.time, p1.processName\norder by 1,2"
    }
   ]
  },
  {
   "title": "Длительность выполнения процесса (ms)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select to_char(p.starttime, 'YYYY-MM-DD HH24:MI:SS')::timestamp as time,\n       p.processName,       \n       avg((EXTRACT('epoch' from p.endtime) - EXTRACT('epoch' from p.starttime)) * 1000) as \" \"\nfrom ProcessInstance p\nwhere p.endtime is not null \nand p.starttime between (timestamp $__timeFrom()) and (timestamp $__timeTo())\ngroup by to_char(p.starttime, 'YYYY-MM-DD HH24:MI:SS'), p.processName\norder by 1,2"
    }
   ]
  },
  {
   "title": "Ошибки",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select to_char(p.endtime, 'YYYY-MM-DD HH24:MI:SS')::timestamp as time,\n       p.processName,       \n       count(1) as \" \"\nfrom ProcessInstance p\nwhere p.error is not null\nand p.endtime between (timestamp $__timeFrom()) and (timestamp $__timeTo())\ngroup by to_char(p.endtime, 'YYYY-MM-DD HH24:MI:SS'), p.processName\norder by 1,2"
    }
   ]
  },
  {
   "title": "Завершено шагов в секунду",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select to_char(n.endtime, 'YYYY-MM-DD HH24:MI:SS')::timestamp as time,\n       p.processName,\n       count(1) as \" \"\nfrom ProcessInstance p\njoin NodeInstance n on n.processinstanceid = p.id and n.endtime is not null\nwhere n.endtime between (timestamp $__timeFrom()) and (timestamp $__timeTo())\ngroup by to_char(n.endtime, 'YYYY-MM-DD HH24:MI:SS'), p.processName\norder by 1,2"
    }
   ]
  }
 ]
}